version: '2.3'
services:
  php-exam:
    container_name: phpexam
    image: paolini/phpexam
    volumes:
      - var:/app/var
      - etc:/app/etc
    ports:
      - 8000:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paolini-exam.rule=Host(`exam.caps.dm.unipi.it`)"
      - "traefik.http.routers.paolini-exam.tls.certresolver=le"
volumes:
  var:
  etc: